[package]
name = "cli-trans"
version = "0.1.0"
authors = ["Wenxuan Zhang <wenxuangm@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.*"
regex = "1.4.3"
reqwest = { version = "0.11.*", features = ["json"] }
scraper = "0.12.*"
serde = { version = "1.0.*", features = ["derive"] }
serde_json = "1.0.*"
tokio = { version = "1.1.*", features = ["full"] }
