[package]
name = "clitrans"
version = "0.1.0"
authors = ["Wenxuan Zhang <wenxuangm@gmail.com>"]
description = "Yet another command-line translator"
categories = ["command-line-utilities"]
homepage = "https://github.com/wfxr/clitrans"
keywords = [
    "translator",
    "tool",
]
license = "MIT/Apache-2.0"
exclude = [
    "/completions"
]
repository = "https://github.com/wfxr/clitrans"
edition = "2018"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1"
colored = "2.0"
itertools = "0.10"
regex = "1.4"
reqwest = { version = "0.11", features = ["json", "gzip"] }
rodio = "0.13"
scraper = "0.12"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
structopt = { version = "0.3", features = ["wrap_help"] }
tokio = { version = "1.1", features = ["full"] }

[profile.release]
lto = true
codegen-units = 1

[build-dependencies]
structopt = { version = "0.3", features = ["wrap_help"] }
