complete -c clitrans -n "__fish_use_subcommand" -s e -l engine -d 'Translate engine'
complete -c clitrans -n "__fish_use_subcommand" -l explanations -d 'How many explanations to display'
complete -c clitrans -n "__fish_use_subcommand" -l phonetics -d 'How many phonetics to display'
complete -c clitrans -n "__fish_use_subcommand" -s p -l phrases -d 'How many web phrases to display'
complete -c clitrans -n "__fish_use_subcommand" -s a -l audio -d 'Play pronounce audio (if any)'
complete -c clitrans -n "__fish_use_subcommand" -s h -l help -d 'Prints help information'
complete -c clitrans -n "__fish_use_subcommand" -s V -l version -d 'Prints version information'
complete -c clitrans -n "__fish_use_subcommand" -f -a "completion" -d 'Generate shell completion file'
complete -c clitrans -n "__fish_use_subcommand" -f -a "help" -d 'Prints this message or the help of the given subcommand(s)'
complete -c clitrans -n "__fish_seen_subcommand_from completion" -s h -l help -d 'Prints help information'
complete -c clitrans -n "__fish_seen_subcommand_from completion" -s V -l version -d 'Prints version information'
complete -c clitrans -n "__fish_seen_subcommand_from help" -s h -l help -d 'Prints help information'
complete -c clitrans -n "__fish_seen_subcommand_from help" -s V -l version -d 'Prints version information'
